### PR TITLE
Increase version number for NPM

### PR DESCRIPTION
**Pull request by martynchamberlin**
Currently I'm managing https://www.npmjs.com/package/ng-zinfinitescroll since there isn't an official NPM for this fork of infiniteScroll.

### CODE REVIEW

**Comment by LightZam** [comment]
i just found out there is already a npm for this.

https://www.npmjs.com/package/angular-zinfinitescroll

and i didn't notice that, i will put that info on readme

**Comment by martynchamberlin** [comment]
@LightZam Yeah... except that NPM hasn't been updated in a while! Which is why I created https://www.npmjs.com/package/ng-zinfinitescroll :)

Thanks

**Comment by LightZam** [comment]
i think you got the point.
maybe i should maintain both npm and bower myself, otherwise when it become out of date, i have nothing to do with it.

**Comment by martynchamberlin** [comment]
@LightZam If you wanted to do that, that'd be great! Would you like for me to grant you modification access to my package?

**Comment by LightZam** [comment]
i already create one for this purpose
maybe you can use it : https://www.npmjs.com/package/zinfinitescroll

**Comment by martynchamberlin** [comment]
Awesome! Thanks. I'll use this one and close my custom one.

**Pull request merged**
